version: '3'

services:
  web:
    image: jannemattila/webapp-pgbouncer
  pgbouncer:
    image: pgbouncer/pgbouncer
    ports:
      - "5439:5439"
    environment:
      - POSTGRES_PASSWORD=passwordhere
      - DATABASES_HOST=yourinstancename.postgres.database.azure.com
      - DATABASES_PORT=5432
      - DATABASES_USER=userhere@yourinstancename.postgres.database.azure.com
      - DATABASES_PASSWORD=passwordhere
      - DATABASES_DBNAME=postgres
      - PGBOUNCER_SERVER_TLS_SSLMODE=verify-ca
      - PGBOUNCER_LISTEN_PORT=5439
