version: '3'

services:
  web:
    image: jannemattila/webapp-pgbouncer
  pgbouncer:
    image: pgbouncer/pgbouncer
    ports:
      - "5439:5439"
    environment:
      - POSTGRES_PASSWORD=password
      - DATABASES_HOST=postgres
      - DATABASES_PORT=5432
      - DATABASES_USER=postgres
      - DATABASES_PASSWORD=password
      - DATABASES_DBNAME=postgres
      - PGBOUNCER_LISTEN_PORT=5439
